spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/postgres?currentSchema=spring_data_jpa_java"
    username: "{username}"
    password: "{password}"

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        dialect: "org.hibernate.dialect.PostgreSQLDialect"